POST http://localhost/JAVAEE/estacion/index.php HTTP/1.1
content-type: application/json

{"id_estacion":2,"fecha":"2021-05-18 12:30:33","temperatura":23.4,"presion":42.4,"velocidad_viento":34.60,"direccion_viento":0,"radiacion_solar":8,"radiacion_uv":4,"humedad":23.50}